#!/bin/bash

get-mod-signature ()
{
	local MODULE="$1"

	local mawk_prog='BEGIN { RS="_"; str=""; }
	{
		str=str substr($0,1,1);
	}
	END { print str; }'

	echo "$MODULE" | mawk "$mawk_prog"
}

build-division ()
{
	local SOURCE_TEXT="$1"

	local LIBRARY="$2"
	local UNIVERSE="$3"
	local LANGUAGE="$4"
	local MODULE="$5"
	local DIVISION="$6"
	local READING="$7"
	local PERMISSION="$8"

	local mawk_prog='BEGIN {
		PREFIX=substr(LIBRARY,1,1) substr(UNIVERSE,1,1) substr(LANGUAGE,1,1);
		DIV_PREFIX=PREFIX MOD_SIGNATURE;
		SUFFIX=substr(READING,1,1) substr(PERMISSION,1,1);

		SIGNATURE=PREFIX "_" MODULE "_" SUFFIX;
		DIV_SIGNATURE=DIV_PREFIX "_" DIVISION "_" SUFFIX;
	}
	{
		gsub("<<<LIBRARY>>>", LIBRARY);
		gsub("<<<UNIVERSE>>>", UNIVERSE);
		gsub("<<<LANGUAGE>>>", LANGUAGE);
		gsub("<<<MODULE>>>", MODULE);
		gsub("<<<DIVISION>>>", DIVISION);
		gsub("<<<READING>>>", READING);
		gsub("<<<PERMISSION>>>", PERMISSION);

		gsub("<<<SIGNATURE>>>", SIGNATURE);
		gsub("<<<DIV_SIGNATURE>>>", DIV_SIGNATURE);

		print $0;
	}'

	echo "$SOURCE_TEXT"							|
	mawk									\
		-v LIBRARY="$LIBRARY"						\
		-v UNIVERSE="$UNIVERSE"						\
		-v LANGUAGE="$LANGUAGE"						\
		-v MODULE="$MODULE"						\
		-v DIVISION="$DIVISION"						\
		-v READING="$READING"						\
		-v PERMISSION="$PERMISSION"					\
		-v MOD_SIGNATURE="$(get-mod-signature "$MODULE")"		\
										\
	"$mawk_prog"
}

build-division "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"

