#!/bin/bash

LIBRARY="$1"
UNIVERSE="$2"
LANGUAGE="$3"
MODULE="$4"
READING="$5"
PERMISSION="$6"

SOURCE_DIR="$(if [ -n "$7" ]; then echo "$7"; else echo "files.source"; fi)"

OUT_DIR="$LIBRARY-$UNIVERSE-$LANGUAGE-$MODULE"

if [ ! -d "$OUT_DIR" ]
then
	mkdir "$OUT_DIR"
fi

# doesn't reuse source texts because it can't assume they're identical for custom builds.

cat divisions.txt |
while read division
do
	SOURCE_TEXT="$(build_source "$LIBRARY" "$UNIVERSE" "$LANGUAGE" "$MODULE" "$division" "$READING" "$PERMISSION" "$SOURCE_DIR")"
	build_division "$SOURCE_TEXT" "$LIBRARY" "$UNIVERSE" "$LANGUAGE" "$MODULE" "$division" "$READING" "$PERMISSION"
done

