#!/bin/bash

LIBRARY="$1"
UNIVERSE="$2"
LANGUAGE="$3"
READING="$5"
PERMISSION="$6"

OUT_DIR="$LIBRARY-$UNIVERSE-$LANGUAGE-$MODULE"

if [ ! -d "$OUT_DIR" ]
then
	mkdir "$OUT_DIR"
fi

# doesn't reuse source texts because it can't assume they're identical for custom builds.

cat "divisions.txt" |
while read division
do
	SOURCE_TEXT="$(build_source "$LIBRARY" "$UNIVERSE" "$LANGUAGE" "$MODULE" "$division" "$READING" "$PERMISSION")"
	DIVISION_TEXT="$(build_division "$SOURCE_TEXT" "$LIBRARY" "$UNIVERSE" "$LANGUAGE" "$MODULE" "$division" "$READING" "$PERMISSION")"

	echo "$DIVISION_TEXT" > "$OUT_DIR/$division-$PERMISSION.h"
done

