#!/bin/bash

build-narrative ()
{
	local SOURCE_TEXT="$1"

	local LIBRARY="$2"
	local UNIVERSE="$3"
	local LANGUAGE="$4"
	local MODULE="$5"
	local READING="$6"
	local PERMISSION="$7"

	local mawk_prog='
	{
		gsub("<<<LIBRARY>>>", LIBRARY);
		gsub("<<<UNIVERSE>>>", UNIVERSE);
		gsub("<<<LANGUAGE>>>", LANGUAGE);
		gsub("<<<MODULE>>>", MODULE);
		gsub("<<<READING>>>", READING);
		gsub("<<<PERMISSION>>>", PERMISSION);

		gsub("<<<U_LIBRARY>>>", toupper(LIBRARY));
		gsub("<<<U_UNIVERSE>>>", toupper(UNIVERSE));
		gsub("<<<U_LANGUAGE>>>", toupper(LANGUAGE));
		gsub("<<<U_MODULE>>>", toupper(MODULE));
		gsub("<<<U_READING>>>", toupper(READING));
		gsub("<<<U_PERMISSION>>>", toupper(PERMISSION));

		print $0;
	}'

	echo "$SOURCE_TEXT"							|
	mawk									\
		-v LIBRARY="$LIBRARY"						\
		-v UNIVERSE="$UNIVERSE"						\
		-v LANGUAGE="$LANGUAGE"						\
		-v MODULE="$MODULE"						\
		-v READING="$READING"						\
		-v PERMISSION="$PERMISSION"					\
										\
	"$mawk_prog"
}

build-narrative "$1" "$2" "$3" "$4" "$5" "$6" "$7"

