#!/bin/bash

make-narrative ()
{
	local LIBRARY="$1"
	local UNIVERSE="$2"
	local LANGUAGE="$3"
	local MODULE="$4"
	local READING="$5"
	local PERMISSION="$6"

	local U_LIBRARY="$(echo "$LIBRARY" | mawk '{ print toupper($0); }')"
	local U_UNIVERSE="$(echo "$UNIVERSE" | mawk '{ print toupper($0); }')"
	local U_LANGUAGE="$(echo "$LANGUAGE" | mawk '{ print toupper($0); }')"
	local U_MODULE="$(echo "$MODULE" | mawk '{ print toupper($0); }')"
	local U_READING="$(echo "$READING" | mawk '{ print toupper($0); }')"
	local U_PERMISSION="$(echo "$PERMISSION" | mawk '{ print toupper($0); }')"

	local N_PATH="$(if [ "$READING" = "assemblic" ]; then echo "../../module-symbolic/narrative/"; else echo ""; fi)"

	local mawk_prog='
	{
		gsub("<<<N_PATH>>>", "'"$N_PATH"'");

		gsub("<<<LIBRARY>>>", "'"$LIBRARY"'");
		gsub("<<<UNIVERSE>>>", "'"$UNIVERSE"'");
		gsub("<<<LANGUAGE>>>", "'"$LANGUAGE"'");
		gsub("<<<MODULE>>>", "'"$MODULE"'");
		gsub("<<<READING>>>", "'"$READING"'");
		gsub("<<<PERMISSION>>>", "'"$PERMISSION"'");

		gsub("<<<U_LIBRARY>>>", "'"$U_LIBRARY"'");
		gsub("<<<U_UNIVERSE>>>", "'"$U_UNIVERSE"'");
		gsub("<<<U_LANGUAGE>>>", "'"$U_LANGUAGE"'");
		gsub("<<<U_MODULE>>>", "'"$U_MODULE"'");
		gsub("<<<U_READING>>>", "'"$U_READING"'");
		gsub("<<<U_PERMISSION>>>", "'"$U_PERMISSION"'");

		print $0;
	}'

	cat "text_files/narrative.txt" |
	mawk "$mawk_prog" > "$LIBRARY-$UNIVERSE-$LANGUAGE-$MODULE-$PERMISSION.h"
}

make-narrative "$1" "$2" "$3" "$4" "$5" "$6"

