#!/bin/bash

get-text()
{
	local FILE_NAME="$1"
	local DIVISION="$2"
	local MODULE_DIR="$3"
	local SOURCE_DIR="$4"

	local TEXT_FILE=""

	if [ -f "$MODULE_DIR/$FILE_NAME-$DIVISION.txt" ]
	then
		TEXT_FILE="$MODULE_DIR/$FILE_NAME-$DIVISION.txt"

	elif [ -f "$MODULE_DIR/$FILE_NAME.txt" ]
	then
		TEXT_FILE="$MODULE_DIR/$FILE_NAME.txt"
	else
		TEXT_FILE="$SOURCE_DIR/$FILE_NAME.txt"
	fi

	cat "$TEXT_FILE"
}

build-source ()
{
	local LIBRARY="$1"
	local UNIVERSE="$2"
	local LANGUAGE="$3"
	local MODULE="$4"
	local DIVISION="$5"
	local READING="$6"
	local PERMISSION="$7"
#
	local SOURCE_DIR="files.source"
	local MODULE_DIR="$SOURCE_DIR$(if [ -n "$8" ]; then echo ".$8"; else echo ""; fi)"
#
	local COPYRIGHT_TEXT=""
	local DISCOURSE_TEXT=""
	local BODY_TEXT=""

	local DEPENDENCIES_TEXT=""
	local SYMBOLIC_TEXT=""
	local ASSEMBLIC_TEXT=""
	local PROCEDURAL_TEXT=""
#
	COPYRIGHT_TEXT="$(get-text "copyright" "$DIVISION" "$MODULE_DIR" "$SOURCE_DIR")"

	local DISCOURSE_NAME=""
	local BODY_NAME=""

	if [ "$DIVISION" = "permission" ]
	then
		DISCOURSE_NAME="permission"
	else
		DISCOURSE_NAME="division"

		DEPENDENCIES_TEXT="$(get-text "dependencies" "$DIVISION" "$MODULE_DIR" "$SOURCE_DIR")\n\n"

		if [ "$DIVISION" = "inductor" ]
		then
			BODY_NAME="inductor"
		else
			BODY_NAME="sap"

			SYMBOLIC_TEXT="\n$(get-text "symbolic-$LIBRARY" "$DIVISION" "$MODULE_DIR" "$SOURCE_DIR")\n"
			ASSEMBLIC_TEXT="\n$(get-text "assemblic-$LIBRARY" "$DIVISION" "$MODULE_DIR" "$SOURCE_DIR")"

			if [ "$READING" = "assemblic" ]
			then
				PROCEDURAL_TEXT="\n\n$(get-text "procedural-$LIBRARY" "$DIVISION" "$MODULE_DIR" "$SOURCE_DIR")"
			fi
		fi

		BODY_TEXT="$(get-text "body-$BODY_NAME" "$DIVISION" "$MODULE_DIR" "$SOURCE_DIR")"
	fi

	DISCOURSE_TEXT="$(get-text "discourse-$DISCOURSE_NAME" "$DIVISION" "$MODULE_DIR" "$SOURCE_DIR")"
#
	local mawk_prog='
	{
		gsub("<<<DISCOURSE_TEXT>>>", DISCOURSE_TEXT);
		gsub("<<<BODY_TEXT>>>", BODY_TEXT);

		gsub("<<<DEPENDENCIES_TEXT>>>", DEPENDENCIES_TEXT);
		gsub("<<<SYMBOLIC_TEXT>>>", SYMBOLIC_TEXT);
		gsub("<<<ASSEMBLIC_TEXT>>>", ASSEMBLIC_TEXT);
		gsub("<<<PROCEDURAL_TEXT>>>", PROCEDURAL_TEXT);

		print $0;
	}'

	echo "$COPYRIGHT_TEXT"							|
	mawk									\
		-v DISCOURSE_TEXT="$DISCOURSE_TEXT"				\
		-v BODY_TEXT="$BODY_TEXT"					\
		-v DEPENDENCIES_TEXT="$DEPENDENCIES_TEXT"			\
		-v SYMBOLIC_TEXT="$SYMBOLIC_TEXT"				\
		-v ASSEMBLIC_TEXT="$ASSEMBLIC_TEXT"				\
		-v PROCEDURAL_TEXT="$PROCEDURAL_TEXT"				\
										\
	"$mawk_prog"
}

build-source "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"

