#!/bin/bash

LIBRARY="$1"
UNIVERSE="$2"
LANGUAGE="$3"
MODULE="$4"
READING="$5"
PERMISSION="$6"

if [ ! -d "$LIBRARY-$UNIVERSE-$LANGUAGE-$MODULE-$READING" ]; then mkdir "$LIBRARY-$UNIVERSE-$LANGUAGE-$MODULE-$READING"; fi

build_module_division "$LIBRARY" "$UNIVERSE" "$LANGUAGE" "$MODULE" "alias" "$READING" "$PERMISSION"
build_module_division "$LIBRARY" "$UNIVERSE" "$LANGUAGE" "$MODULE" "inductor" "$READING" "$PERMISSION"
build_module_division "$LIBRARY" "$UNIVERSE" "$LANGUAGE" "$MODULE" "identity" "$READING" "$PERMISSION"
build_module_division "$LIBRARY" "$UNIVERSE" "$LANGUAGE" "$MODULE" "embedding" "$READING" "$PERMISSION"
build_module_division "$LIBRARY" "$UNIVERSE" "$LANGUAGE" "$MODULE" "structure" "$READING" "$PERMISSION"

