#!/bin/bash

build-division ()
{
	local SOURCE_TEXT="$1"

	local LIBRARY="$2"
	local UNIVERSE="$3"
	local LANGUAGE="$4"
	local MODULE="$5"
	local DIVISION="$6"
	local READING="$7"
	local PERMISSION="$8"

	local mawk_prog='
	{
		gsub("<<<LIBRARY>>>", LIBRARY);
		gsub("<<<UNIVERSE>>>", UNIVERSE);
		gsub("<<<LANGUAGE>>>", LANGUAGE);
		gsub("<<<MODULE>>>", MODULE);
		gsub("<<<DIVISION>>>", DIVISION);
		gsub("<<<READING>>>", READING);
		gsub("<<<PERMISSION>>>", PERMISSION);

		print $0;
	}'

	echo "$SOURCE_TEXT"						|
	mawk								\
		-v LIBRARY="$LIBRARY"					\
		-v UNIVERSE="$UNIVERSE"					\
		-v LANGUAGE="$LANGUAGE"					\
		-v MODULE="$MODULE"					\
		-v DIVISION="$DIVISION"					\
		-v READING="$READING"					\
		-v PERMISSION="$PERMISSION"				\
									\
	"$mawk_prog"
}

build-division "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"

