#!/bin/bash

make-division ()
{
	local LIBRARY="$1"
	local UNIVERSE="$2"
	local LANGUAGE="$3"
	local MODULE="$4"
	local DIVISION="$5"
	local READING="$6"
	local PERMISSION="$7"

	local mawk_prefix_prog='BEGIN { p=""; }
	{
		p=p substr($0, 1, 1);
	}
	END { print p; }'

	local PREFIX="$(echo -e "$LIBRARY\n$UNIVERSE\n$LANGUAGE" | mawk "$mawk_prefix_prog")"
	local E_PREFIX="$(echo "$MODULE" | mawk '{ print "'"$PREFIX"'" substr($0, 1, 1); }')"
	local SUFFIX="$(echo -e "$READING\n$PERMISSION" | mawk "$mawk_prefix_prog")"

	local SIGNATURE="$PREFIX""_$MODULE""_$SUFFIX"
	local E_SIGNATURE="$E_PREFIX""_$DIVISION""_$SUFFIX"

	local mawk_prog='
	{
		gsub("<<<LIBRARY>>>", "'"$LIBRARY"'");
		gsub("<<<UNIVERSE>>>", "'"$UNIVERSE"'");
		gsub("<<<LANGUAGE>>>", "'"$LANGUAGE"'");
		gsub("<<<MODULE>>>", "'"$MODULE"'");
		gsub("<<<DIVISION>>>", "'"$DIVISION"'");
		gsub("<<<READING>>>", "'"$READING"'");
		gsub("<<<PERMISSION>>>", "'"$PERMISSION"'");

		gsub("<<<SIGNATURE>>>", "'"$SIGNATURE"'");
		gsub("<<<E_SIGNATURE>>>", "'"$E_SIGNATURE"'");

		print $0;
	}'

	local FILE="$(if [ "$DIVISION" = "alias" -o "$DIVISION" = "inductor" ]; then echo "$DIVISION"; else echo "discourse"; fi)"

	cat "text_files/$FILE.txt" |
	mawk "$mawk_prog" > "$LIBRARY-$UNIVERSE-$LANGUAGE-$MODULE/$LIBRARY-$UNIVERSE-$LANGUAGE-$MODULE-$DIVISION-$PERMISSION.h"
}

make-division "$1" "$2" "$3" "$4" "$5" "$6" "$7"

