#!/bin/bash

LIBRARY="$1"
UNIVERSE="$2"
LANGUAGE="$3"
MODULE="$4"
READING="$5"
PERMISSION="$6"

OUT_DIR="$LIBRARY-$UNIVERSE-$LANGUAGE-$MODULE"

if [ ! -d "$OUT_DIR" ]
then
	mkdir "$OUT_DIR"
fi

# doesn't reuse source texts because it can't assume they're identical for custom builds.

cat "divisions.txt"	|
while read division
do
	SOURCE_TEXT="$(build_source "$LIBRARY" "$UNIVERSE" "$LANGUAGE" "$MODULE" "$division" "$READING" "$PERMISSION")"
	DIVISION_TEXT="$(build_division "$SOURCE_TEXT" "$LIBRARY" "$UNIVERSE" "$LANGUAGE" "$MODULE" "$division" "$READING" "$PERMISSION")"
	OUT_FILE="$(if [ "$division" = "permission" ]; then echo "$PERMISSION.h"; else echo "$division-$PERMISSION.hpp"; fi)"

	echo "$DIVISION_TEXT" > "$OUT_DIR/$OUT_FILE"
done

