#!/bin/bash

#LIBRARY="${1%-*}"
#READING_DIR="${1#*-}"

LIBRARY="$1"
UNIVERSE="$2"
LANGUAGE="$3"
MODULE="$4"
READING="$5"

ls "$LIBRARY-$READING" |
while read file
do
	cp "$LIBRARY-$READING/$file" "../module-$READING/discourse/$LIBRARY-$UNIVERSE-$LANGUAGE-$MODULE-$file"
done

